"use client"
import Navbar from "@/components/shared/Navbar";
import "./globals.css";
import AuthProvider from "@/providers/authProvider";
import { usePathname } from "next/navigation";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const showNavbar = pathname !== "/dashboard" && pathname !== "/dashboard/launch_event_form";

  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {showNavbar && <Navbar />}
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
