import AuthProvider from "@/providers/authProvider";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {

    return (
        <html lang="en">
            <body>
                <AuthProvider>
                    <div className="flex min-h-screen">
                        {/* Sidebar */}
                        <div className="w-[280px] bg-[#001427] h-screen sticky top-0 overflow-y-auto flex-shrink-0">
                            <h1 className="text-white font-bold text-4xl text-center py-6">Dashboard</h1>
                            {/* Sidebar content like buttons or links */}
                            <ul>
                                <li className="py-2 px-4 hover:bg-[#0a2839]">
                                    <a href="/dashboard">Dashboard</a>
                                </li>
                                <li className="py-2 px-4 hover:bg-[#0a2839]">
                                    <a href="/dashboard/settings">Settings</a>
                                </li>
                                {/* Add more links */}
                            </ul>
                        </div>
                        {/* Main Content */}
                        <div className="flex-1 p-6 overflow-y-auto">
                            {children}
                        </div>
                    </div>
                </AuthProvider>
            </body>
        </html>
    );
}
